### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by i814u2** [octopuss/7-segment-clock#1]
I was having some troubles getting my D1 mini board up and running.

The readme mentions updating the config.h with wifi info, but I don't see any example wifi settings values. After some digging, I saw that you can just let it be, it creates an AP to connect to (Led-clock) and you can config the wifi from there. Maybe an updated readme would help. But, the ESP WiFI manager is cool.

When building, with PlatformIO, I got errors like this:
```
In file included from src/main.cpp:1:
.pio/libdeps/D1_MINI_7_SEGMENT_CLOCK/FastLED/src/FastLED.h:474:25: note: candidate: 'template<EBlockChipsets CHIPSET, int NUM_LANES> static CLEDController& CFastLED::addLeds(CRGB*, int, int)'
  474 |  static CLEDController &addLeds(struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset = 0) {
      |                         ^~~~~~~
.pio/libdeps/D1_MINI_7_SEGMENT_CLOCK/FastLED/src/FastLED.h:474:25: note:   template argument deduction/substitution failed:
src/main.cpp:36:73: error: wrong number of template arguments (3, should be 2)
   36 |   FastLED.addLeds<LED_TYPE, LED_PIN, RGB>(ledsRGB, getRGBWsize(NUM_LEDS));
```

I had to update config.h like so (I added the last line, in this example):
```
//// FastLED
#define LED_PIN D3 // LED data pin to use on ESP
#define LED_TYPE WS2812B // LED Type
```

While you're in config.h, timezone should be adjusted based on information from this site:
https://rainmaker.espressif.com/docs/time-service.html (this is just one site I found, rather than building the value myself)

I also had an error, on first build, about not having the ESPAsyncWebServer headers. I installed `ottowinter/ESPAsyncWebServer-esphome@^3.0.0`, but should I have needed to do that or no?

Finally, I had troubles uploading, until I commented out these lines, from the platformio.ini:
```
; upload_protocol = espota
; upload_port = 192.168.88.45
```

I realize that some of these details may be obvious to folks with more experience, but I'm new to using PlatformIO, so I thought I'd mention them in the hopes that it helps someone else. For instance, once it uploaded via usb to serial, I went through the wifi setup, got the IP, and then updated my local platformio.ini to use that IP. Now it updates over wifi, which is nice.

@octopuss If you could comment on whether I've made any bad changes, or if some were just missed in the repo (since config.h is in the gitignore file), I'd appreciate it. 

### I'll post my current setup, just to follow a decent habit when entering issues:
My PlatformIO info: Core 6.1.4·Home 3.4.3
I'm on a Mac (12.5.1), with M1 pro chip (which shouldn't really matter in this case).

```
Dependency Graph
|-- FastLED @ 3.5.0
|   |-- EspSoftwareSerial @ 6.12.7
|   |-- SPI @ 1.0
|-- ArduinoJson @ 6.19.4
|-- CronAlarms @ 0.1.0
|-- ESPAsyncWiFiManager @ 0.31.0
|   |-- DNSServer @ 1.1.1
|   |   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- ESPAsyncWebServer-esphome @ 3.0.0
|   |   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |   |-- Hash @ 1.0
|   |   |-- ESP8266WiFi @ 1.0
|-- ESPAsyncWebServer-esphome @ 3.0.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- ArduinoOTA @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266mDNS @ 1.2
|   |   |-- ESP8266WiFi @ 1.0
|-- ESP8266WiFi @ 1.0
```

**Comment by octopuss** [comment]
Hi, thank you for your comment, I will look at it. It is possible that you are the first using it :).

 I've plans to update project a little bit because showing temperature is color based currently, and wakes me up during night :) So I'will post the update soon.  The firmware is also ready to be flashed OTA, so you don't have to wait with the clock box "opened"
